#
name: Main Branch Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
        
      - name: Setup Dependencies
        run: |
          gem install bundler
          bundle install --gemfile=Gemfile

      - name: Linting and Styling
        run: |
          gem install rubocop
          rubocop

      - name: Vulnerability Checks
        run: |
          gem install bundler-audit
          bundler-audit update
          bundler-audit check

      - name: Run Unit Tests
        run: |
          gem install rspec
          rspec

      - name: Build Docker Image
        run: |
          docker build -f Dockerfile.main -t ${{ secrets.DOCKER_USERNAME }} .

      - name: Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}
